linters:
  ErbSafety:
    enabled: false

  Rubocop:
    enabled: true
    rubocop_config:
      Layout/InitialIndentation:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false

      Lint/UselessAssignment:
        Enabled: false

      Style/FrozenStringLiteralComment:
        Enabled: false

  AllowedScriptType:
    enabled: true
    disallow_inline_scripts: true

  NoJavascriptTagHelper:
    enabled: false
